### PR TITLE
8.3 rebase on xs

### PR DESCRIPTION
**Pull request by stormi**

### CODE REVIEW

**Review by ydirson — COMMENTED** [review]
Is it a good idea to remove the telemetry user?  I fear it's going to possibly cause issues at some point when upgrading from XS8, like we had with the missing `nagios` user.

**Comment by stormi** [comment]
I'd like to avoid having to explain to users that no, we don't phone home, but yes, there's a user named "telemetry" which serves no purpose :sweat:

**Comment by ydirson** [comment]
> I'd like to avoid having to explain to users that no, we don't phone home, but yes, there's a user named "telemetry" which serves no purpose 😓

Then I fear we have to be ready to patch the installer to add a specific upgrade procedure to upgrade from platform 3.4, which in turn would mean we have to bump the platform number independently of XS, which *they* are the upstream. It is hard to rule out getting into the same kind of issue we had with the `nagios` user previously, and diverging the platform is likely something we don't want to do.

Would "We share a common platform with XS and this is here to make sure users can upgrade from XS8" not be sufficient?

For now though there files owned by this user/group is limited so this may not break anything, but I'm not sure it is sufficient for an excuse:

```
[root@xenserver-axftaywy ~]# find / -xdev \( -user telemetry -o -group telemetry \) -ls
139311    4 drwx------   2 telemetry telemetry     4096 Feb 23 00:26 /var/telemetry
140766    4 -rw-r--r--   1 telemetry telemetry      145 Jun  6 21:54 /var/telemetry/telemetry.data
```

**Comment by stormi** [comment]
Given that what used to make the upgrade fail was the lack of the `certuser` group and that we now have it, that I have verified that the upgrade works from XS 8, that I haven't found any mention of `telemetry` (even less `/var/telemetry`) in the installer, and that we don't know of any file which would belong to the `telemetry` user or group and that would be preserved by an upgrade, I'm ready to take this risk.

**Comment by stormi** [comment]
Koji build to v8.3-incoming: http://koji.xcp-ng.org/taskinfo?taskID=56405

**Pull request merged**
